# https://www.docker.elastic.co
FROM docker.elastic.co/kibana/kibana:8.12.0

# Install the Kibana Prometheus Exporter
RUN bin/kibana-plugin install https://github.com/qualifio/kibana-prometheus-exporter/releases/download/8.12.0/kibanaPrometheusExporter-8.12.0.zip