name: "Test & Coverage"

on:
  pull_request:
    branches: [ main ]

jobs:
  test_and_coverage:
    name: "Test & Coverage"
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        repository: elastic/kibana
        ref: refs/heads/main

    - uses: actions/checkout@v4
      with:
        path: 'plugins/kibana-prometheus-exporter'

    - name: Install workflow dependencies
      run: sudo apt-get install -y jq

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Set up Kibana development environment
      run: yarn kbn bootstrap

    - name: Install plugin dependencies
      working-directory: plugins/kibana-prometheus-exporter
      run: yarn install

    - name: Run tests
      working-directory: plugins/kibana-prometheus-exporter
      run: yarn test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
