name: Release Wiki

on:
  workflow_dispatch:
  push:
    paths:
      - 'wiki/**'
    branches:
      - main

jobs:
  release_plugin:
    name: Release Wiki
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      fail-fast: false

    steps:
      - name: Check out Kibana Prometheus Exporter
        uses: actions/checkout@v2
        with:
          path: "kibana-prometheus-exporter"

      - name: Check out Kibana Prometheus Exporter Wiki
        uses: actions/checkout@v2
        with:
          repository: "qualifio/kibana-prometheus-exporter.wiki"
          ref: master
          path: "kibana-prometheus-exporter.wiki"

      - name: Configure Git
        run: |
          git config --global --add safe.directory /kibana-prometheus-exporter.wiki
          git config --global user.email "qualifio@users.noreply.github.com"
          git config --global user.name "qualifio"

      - name: Clean wiki
        working-directory: kibana-prometheus-exporter.wiki
        run: rm -rf ./*

      - name: Copy wiki files
        run: cp -a kibana-prometheus-exporter/wiki kibana-prometheus-exporter.wiki

      - name: Update wiki remote
        working-directory: kibana-prometheus-exporter.wiki
        run: |
          git add .
          git commit -m "action: Update Wiki"
          git push origin master
