name: "Release Plugin"

on: workflow_dispatch

jobs:
  release_plugin:
    name: Release Plugin
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        repository: elastic/kibana
        ref: refs/heads/main

    - uses: actions/checkout@v4
      with:
        path: 'plugins/kibana-prometheus-exporter'

    - name: Install workflow dependencies
      run: sudo apt-get install -y jq

    - name: Detect Node version
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvmrc

    - name: Use Node.js ${{ steps.nvmrc.outputs.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}'

    - name: Set up Kibana Development Environment
      run: yarn kbn bootstrap

    - name: Build plugin
      working-directory: plugins/kibana-prometheus-exporter
      run: echo "${{ github.ref_name }}" | yarn build

    - name: Create checksum manifest
      working-directory: plugins/kibana-prometheus-exporter/build
      run: ../utils/checksum ./*.zip >checksum.json

    - name: Create release notes
      working-directory: plugins/kibana-prometheus-exporter
      run: cp ./utils/RELEASE_TEMPLATE.md ./build && ./utils/create_release_template ./build/RELEASE_TEMPLATE.md

    - name: Sanity Check
      working-directory: plugins/kibana-prometheus-exporter/build
      run: ls -la && cat RELEASE_TEMPLATE.md

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        body_path: plugins/kibana-prometheus-exporter/build/RELEASE_TEMPLATE.md
        prerelease: false
        draft: true
        files: |
          plugins/kibana-prometheus-exporter/build/checksum.json
          plugins/kibana-prometheus-exporter/build/kibanaPrometheusExporter-${{ github.ref_name }}.zip
